# Generated by Django 4.2.3 on 2023-09-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myyl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
