# Generated by Django 4.2.3 on 2023-09-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myyl', '0003_alter_bus_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bus',
        ),
    ]
