# Generated by Django 4.2.3 on 2023-09-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myyl', '0004_delete_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peopleNumber', models.IntegerField()),
                ('in_count', models.IntegerField()),
                ('out_count', models.IntegerField()),
                ('congestion', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
